### ISSUE TITLE
Feature Request: XML String to JSON

### ISSUE THREAD

**Issue by forensicmatt** [omerbenamram/evtx#73]
How hard would it be to implement the JSON parsing from a XML string? This would help with testing where you want to validate the output json structure against specific XML events. Could also be useful for something that uses Windows API that retrieves the XML string and wants to convert it to JSON and maintain a 1 to 1 structure with this library.

**Comment by omerbenamram** [comment]
This is actually pretty trivial to implement - we could just use a `quick-xml` reader and translate the events it yields to the input `JsonOutput` expects, it should be around less than 50 lines of code.

But since we currently doesn't interact with winapi at all, this doesn't offer any utility to this library, and so this falls out of scope of this project, expect maybe as a testing utility.
 
Since `JsonOutput` is public, it should be possible to import it and gain structual similarity in a foreign library using this method.

**Comment by forensicmatt** [comment]
then +1 for adding it as a testing utility ;)

**Comment by omerbenamram** [comment]
Added :)
